### ISSUE TITLE
Python request error

### ISSUE THREAD

**Issue by acambas** [blacklight/nvim-http#9]
Hello, 
I'm trying to use the plugin but when i try to run it i get this error:

```
Http Error invoking 'python_execute' on channel 160 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/sasha.cambas/.local/share/nvim/lazy/nvim-http/autoload/../python/nvim_http/client.py", line 63, in http_run
    request = parse_http_request(text, **env)
TypeError: nvim_http.parser.parse_http_request() argument after ** must be a mapping, not str
```

here's the http file example:

```
###
GET  https://reqres.in/api/users

```

Some extra info about my setup:
- macos 14.3
- NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1703358377
- python --version = Python 3.9.10

**Comment by blacklight** [comment]
This is probably a duplicate of #15, and most likely due to missing newline or comment line at the end of the request.

I have just tested a request in the same format with the latest version and it works.

Keep in mind to run `:UpdateRemotePlugins` after updating the plugin.

Feel free to reopen the issue if the problem persists.
